/// Flutter icons TargetSistemasTesteIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TargetSistemasTesteIcons
///      fonts:
///       - asset: fonts/TargetSistemasTesteIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TargetSistemasTesteIcons {
  TargetSistemasTesteIcons._();

  static const _kFontFam = 'TargetSistemasTesteIcons';
  static const String? _kFontPkg = null;

  static const IconData edit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
